s3_bucket_name       = "terraform-aws-backend-bucket"
s3_bucket_encryption = "AES256"
DynamoDB_name        = "terraform-aws-backend-locks"
region               = "us-east-2"
backend_key          = "global/s3/terraform.tfstate"